"""
TensorFlow LSTM text classifier.

This reads Parquet generated by the PySpark ETL job.
"""

import argparse
from pathlib import Path

import pandas as pd
import tensorflow as tf

from common import read_parquet


def make_model(vocab_size: int = 5000, seq_len: int = 64) -> tf.keras.Model:
    return tf.keras.Sequential([
        tf.keras.layers.Input(shape=(seq_len,)),
        tf.keras.layers.Embedding(vocab_size, 64),
        tf.keras.layers.LSTM(64),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--train_parquet", required=True)
    parser.add_argument("--valid_parquet", required=True)
    parser.add_argument("--output_dir", default="artifacts/lstm")
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--max_tokens", type=int, default=5000)
    parser.add_argument("--seq_len", type=int, default=64)
    args = parser.parse_args()

    train_df = read_parquet(args.train_parquet)
    valid_df = read_parquet(args.valid_parquet)

    vectorizer = tf.keras.layers.TextVectorization(
        max_tokens=args.max_tokens,
        output_mode="int",
        output_sequence_length=args.seq_len,
    )
    vectorizer.adapt(train_df["text"].astype(str).tolist())

    x_train = vectorizer(tf.constant(train_df["text"].astype(str).tolist()))
    y_train = tf.constant(train_df["label"].astype("float32").tolist())
    x_valid = vectorizer(tf.constant(valid_df["text"].astype(str).tolist()))
    y_valid = tf.constant(valid_df["label"].astype("float32").tolist())

    model = make_model(vocab_size=args.max_tokens, seq_len=args.seq_len)
    model.compile(
        optimizer="adam",
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )

    model.fit(
        x_train,
        y_train,
        validation_data=(x_valid, y_valid),
        epochs=args.epochs,
        batch_size=16,
    )

    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)
    model.save(out / "lstm_text_classifier.keras")
    print(f"Saved model to {out / 'lstm_text_classifier.keras'}")


if __name__ == "__main__":
    main()
